# Example setup options that may be overlaid during setup
# using the --optionsFile option. Run `setup --help` for further
# instructions.
core:
  # Use a JWT claim other than "sub" for the OIDC User ID. 
  #
  #  Authentication.oidcUserIdField: jwt_claim
  #
  # Add policy configuration keys here. The value for a policy 
  # configuration key may be provided via an environment variable 
  # using the notation '${environment-variable}'.
  #
  #  PolicyConfigurationKeyName: PolicyConfigurationKeyValue
keystores:
  # Define key stores used by policy information providers here.
  #
  #  - name: CustomKeyStore
  #    resource: /path/to/custom-keystore.jks
  #    password: keystore-password
truststores:
  # Define trust stores used by policy information providers here.
  #
  #  - name: CustomTrustStore
  #    resource: /path/to/custom-truststore.jks
  #    password: truststore-password
deploymentPackageData:
  # Define a key store to use for signing deployment packages here.
  #
  #  contentType: json
  #  keystore:
  #    resource: /path/to/deployment-package-signing-keystore.jks
  #    password: keystore-password
  #  securityLevel: signed
  #  signingKey:
  #    alias: signing-cert-alias
  #    password: private-key-password
deploymentPackageStores:
  # Define deployment package store publishing targets here.
  #
  # - name: Filesystem store
  #   description: File system directory store
  #   type: filesystem
  #   path: /path/to/deployment-package-store/
  # - name: Signed filesystem store
  #   description: Signed file system directory store
  #   type: filesystem
  #   path: /path/to/signed-deployment-package-store/
  #   securityLevel: signed
  #   keystore:
  #     resource: /path/to/deployment-package-signing-keystore.jks
  #     password: keystore-password
  #   signingKey:
  #     alias: signing-cert-alias
  #     password: private-key-password
  # - name: S3 bucket store
  #   description: AWS S3 bucket store
  #   type: s3bucket
  #   securityLevel: unsigned
  #   config:
  #     bucket: store-bucket-name
  #     prefix: store-prefix
  #     endpoint: https://s3.amazonaws.com
  #     region: us-east-2
  #     accessKey: aws-access-key
  #     secretKey: aws-secret-key
  #
  # - name: Azure blob storage store
  #   description: Microsoft Azure blob storage store
  #   type: azure
  #   securityLevel: unsigned
  #   config:
  #     connection-string: DefaultEndpointsProtocol=[http|https];AccountName=myAccountName;AccountKey=myAccountKey
  #     container: azure-blob-storage-container-name
  #     prefix: azure-blob-storage-prefix
  #
securityHeaders:
  # Configure the values that the Policy Editor will set in its
  # responses for the X-Frame-Options, Content-Security-Policy, and/or
  # Access-Control-Allow-Origin HTTP security headers here.
  #
  # X-Frame-Options: "deny"
  # Content-Security-Policy: "default-src https:"
  # Access-Control-Allow-Origin: "*"
ui:
  # Individually configure the OpenID Connect endpoints. This only applies when configuring the Policy Editor
  # to use OpenID Connect for authentication.
  # 
  # authClientConfig:
  #   authWellKnownEndpoints:
  #     issuer: https://identity-server:<port_no>
  #     authorizationEndpoint: https://identity-server:<port_no>/as/authorization.oauth2
  #     jwksUri: https://identity-server:<port_no>/pf/JWKS
  #     tokenEndpoint: https://identity-server:<port_no>/as/token.oauth2
  #     userinfoEndpoint: https://identity-server:<port_no>/idp/userinfo.openid
  #     endSessionEndpoint: https://identity-server:<port_no>/idp/startSLO.ping
  #     introspectionEndpoint: https://identity-server:<port_no>/as/introspect.oauth2
logging:
  level: INFO
  loggers:
    "DataNucleus": ERROR
    "DataNucleus.Enhancer": "OFF"
    "org.glassfish.jersey.internal.Errors": ERROR
    "com.symphonicsoft.policyanalysis.PolicyTranslator": ERROR
    # If instructed to do so by Ping Identity Support, you can enable
    # additional logging for HTTP errors by uncommenting one of the following
    # lines and running setup. This will cause stack trace details about HTTP
    # errors to be recorded to logs/debug.log.
    #
    # To enable additional logging for HTTP 50x errors only:
    # "com.symphonicsoft.rest.BaseExceptionMapper": ERROR
    #
    # To enable additional logging for HTTP 40x and 50x errors:
    # "com.symphonicsoft.rest.BaseExceptionMapper": DEBUG
    "DECISION_AUDIT_LOG":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/decision-audit.log
          archive: true
          maxFileSize: 250MB
          archivedLogFilenamePattern: logs/decision-audit.%i.log.gz
          archivedFileCount: 10
          logFormat: "[%date{ISO8601}] %msg%n"
    "DECISION_DIAGNOSTIC_LOG":
      level: "OFF"
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/decision-diagnostic.log
          archive: true
          maxFileSize: 250MB
          archivedLogFilenamePattern: logs/decision-audit.%i.log.gz
          archivedFileCount: 10
          logFormat: "%msg%n"
    "MANAGEMENT_AUDIT":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/management-audit.log
          archive: false
          archivedLogFilenamePattern: logs/management-audit.%i.log.gz
          archivedFileCount: 10
          logFormat: "[%date{ISO8601}] %msg%n"
    metrics:
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/metrics.log
          maxFileSize: 250MB
          archive: true
          archivedLogFilenamePattern: logs/metrics.%i.log.gz
          archivedFileCount: 10
          logFormat: "logger=metrics, timestamp=%date{yyyyMMdd'T'HHmmss.SSS}, %msg%n"
  appenders:
    - type: console
      threshold: INFO
      target: stdout
      logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
    - type: file
      threshold: DEBUG
      currentLogFilename: logs/debug.log
      maxFileSize: 250MB
      archive: true
      archivedLogFilenamePattern: logs/debug.%i.log.gz
      archivedFileCount: 10
      logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"
    - type: file
      threshold: INFO
      currentLogFilename: logs/authorize-pe.log
      maxFileSize: 250MB
      archive: true
      archivedLogFilenamePattern: logs/authorize-pe.%i.log.gz
      archivedFileCount: 10
      logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
